name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- main

variables:
  StatefileContext: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.Repository.Name)_$(Build.SourceBranchName)
  Subscription: AzureDev2

stages:
- stage: CI
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Create build artifact'
    pool: 
      vmImage: 'windows-latest'
    steps:
    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop

- stage: dev  
  displayName: 'deploy dev'
  variables:
  - group: dev2-variables

  jobs:
  - deployment: dev
    environment: dev
    pool: 
      vmImage: 'windows-latest'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm: $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop
              backendAzureRmResourceGroupName: $(TerraformStateResourceGroup)
              backendAzureRmStorageAccountName: $(TerraformStateStorageAccount)
              backendAzureRmContainerName: $(TerraformStateContainerName)
              environment: 'dev'
              statefileContext: $(StatefileContext)
 
- stage: test  
  displayName: 'deploy test'
  variables:
  - group: dev2-variables

  jobs:  
  - deployment: test
    environment: test
    pool: 
      vmImage: 'windows-latest'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm: $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop
              backendAzureRmResourceGroupName: $(TerraformStateResourceGroup)
              backendAzureRmStorageAccountName: $(TerraformStateStorageAccount)
              backendAzureRmContainerName: $(TerraformStateContainerName)
              environment: 'test'
              statefileContext: $(StatefileContext)

- stage: prod  
  displayName: 'deploy prod'
  variables:
  - group: dev2-variables

  jobs:  
  - deployment: prod
    environment: prod
    pool: 
      vmImage: 'windows-latest'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm: $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop
              backendAzureRmResourceGroupName: $(TerraformStateResourceGroup)
              backendAzureRmStorageAccountName: $(TerraformStateStorageAccount)
              backendAzureRmContainerName: $(TerraformStateContainerName)
              environment: 'prod'
              statefileContext: $(StatefileContext)
